### ISSUE TITLE
segmentation fault during shutdown, sedgem, can't generate output for restart

### ISSUE THREAD

**Issue by evansmn** [derpycode/muffindoc#15]
This is using release v0.9.33.  On completing the simulation, shutdown fails at sedgem shutdown.  Is there any way to recover without having to rerun the experiment?  This is a spinup simulation, running 1e6 years without acceleration.  What I would like to do is use this as a restart file for another spinup simulation, but attempting to do so produces a similar segmentation fault originating with the same line number in genie.job, but after only a few years of simulation/saving.  Below is the error message.  

>>> Initialising SEDGEM module shutdown ...

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f8b700218c2 in ???
#1  0x7f8b70020a55 in ???
#2  0x7f8b6fd6204f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x563636d2b3db in ???
#4  0x563636d05838 in ???
#5  0x56363696a9ca in ???
#6  0x563636973f5e in ???
#7  0x56363695291e in ???
#8  0x7f8b6fd4d249 in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#9  0x7f8b6fd4d304 in __libc_start_main_impl
	at ../csu/libc-start.c:360
#10  0x563636952940 in ???
#11  0xffffffffffffffff in ???
./genie.job: line 357: 1263740 Segmentation fault      ./genie.exe

real	26121m14.894s
user	26117m14.995s
sys	1m44.597s
cp: cannot stat 'fort.2': No such file or directory
ERROR: !!!!!!!!!! ERROR PROCESSING !!!!!!!!!!

Thanks in advance for suggestions on how to proceed.

**Comment by derpycode** [comment]
Hey!
I am not sure I have seen this before -- first -- could you open an 'issue' under cGENIE.muffin? I rarely check the muffin doc repo traffic.
Secondly, can you can upload the base and user-config file you were using?
And ... maybe as a link to a cloud folder -- can you send the entire output of your 1 Myr experiment?
/andy

**Comment by evansmn** [comment]
Closing this comment and reposting with additional information in cgenie.muffin.
